name: Doctor Panel Docker Build and Deploy

on:
  push:
    branches: [ main ]
    paths: [ "Doctor/**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Decode and prepare env file
        working-directory: Doctor
        run: |
          echo "${{ secrets.DOCTOR_ENV_PUBLIC_FILE }}" | base64 -d > .env.build

      - name: Build and Push Docker image
        working-directory: Doctor
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/tabib_online_doctor:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/tabib_online_doctor:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy User Panel to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ~/tabib_online_frontend/doctor

            echo "${{ secrets.DOCTOR_ENV_FILE }}" | base64 -d > ~/tabib_online_frontend/doctor/.env

            docker stop tabib_online_doctor || true
            docker rm tabib_online_doctor || true
            docker image prune -f

            # Pull and run new image
            docker pull ${{ secrets.DOCKER_USERNAME }}/tabib_online_doctor:latest
            docker run -d \
              --name tabib_online_doctor \
              -p 3001:3001 \
              --env-file ~/tabib_online_frontend/doctor/.env \
              --restart unless-stopped \
              ${{ secrets.DOCKER_USERNAME }}/tabib_online_doctor:latest