name: User Panel Docker Build and Deploy

on:
  push:
    branches: [ main ]
    paths: [ "User/**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        working-directory: User
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/tabib_online_user:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/tabib_online_user:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy User Panel to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ~/tabib_online_frontend/user

            echo "${{ secrets.USER_ENV_FILE }}" | base64 -d > ~/tabib_online_frontend/user/.env

            docker stop tabib_online_user || true
            docker rm tabib_online_user || true
            docker image prune -f

            # Pull and run new image
            docker pull ${{ secrets.DOCKER_USERNAME }}/tabib_online_user:latest
            docker run -d \
              --name tabib_online_user \
              -p 3000:3000 \
              --env-file ~/tabib_online_frontend/user/.env \
              --restart unless-stopped \
              ${{ secrets.DOCKER_USERNAME }}/tabib_online_user:latest
